### ISSUE TITLE
contents of public directory

### ISSUE THREAD

**Issue by bhykes1** [matcornic/hugo-learn-doc#5]
Hi,
How do you create the html files in public folder such as public/content/contributing/index.html

**Comment by matcornic** [comment]
For people who might be interested, files in public folder are generated by Hugo. It comes from the tutorial : [Hosting Hugo website in Github Pages](https://gohugo.io/tutorials/github-pages-blog/).

In a nutshell, the public is the generated html pages displayed when you go to the documentation of this theme.
