### ISSUE TITLE
Search index

### ISSUE THREAD

**Issue by wojtpl2** [matcornic/hugo-learn-doc#6]
I've seen that issue [Add generator for a search index](https://github.com/spf13/hugo/pull/1853) is done.
But on the page is still information:

> As the index generation is not yet supported by Hugo (PR #1853), we decided to use lunr index. As soon as the generation of the index will be supported by hugo, we will use the official format.

https://github.com/matcornic/hugo-learn-doc/blob/master/content/basics/installation/index.md#enable-search-functionality

**Comment by matcornic** [comment]
Hi,

PR #1853 is closed, but it does not mean it has been implemented. Look at the last comment, another issue has been created for the feature : #2828. Plan of Hugo community is to implement it for milestone 0.20 of Hugo

I'll change the doc to reference this issue instead :wink:

**Comment by wojtpl2** [comment]
Thanks!

**Comment by matcornic** [comment]
@hauleth No, the milestone 2.0.0 is already covering it. See repo of the theme : https://github.com/matcornic/hugo-theme-learn/milestone/1?closed=1
