### ISSUE TITLE
Configuration of the appearance of the copy-to-clipboard icons

### ISSUE THREAD

**Issue by kamar535** [matcornic/hugo-learn-doc#7]
Thanks for a great Hugo theme! 

For my site I don't want the copy-to-clip-board icon for inline `code` tags but keep it for `code` tags within `pre` tags. I was able to achieve this by adding this css: 

```
:not(pre) > code + span.copy-to-clipboard {
    display: none;
}
```

It would be really handy if it would be possible to configure the appearance of the copy-to-clipboard icons from the `config.toml` file.  Maybe this could be considered for future versions of the theme.

**Comment by matcornic** [comment]
Hey @kamar535 , can you rewrite this issue in the [main repo](https://github.com/matcornic/hugo-theme-learn) and close this one ?

**Comment by kamar535** [comment]
@matcornic Done, see https://github.com/matcornic/hugo-theme-learn/issues/54
